Docs / minimal CI update for Humble
open-rmf/rmf pull request #215
Opened 2022-09-08 04:45 UTC by luca-della-vedova

## Bug fix

### Fixed bug

Yet another doc / CI update for Humble! Minimal version to avoid introducing too much changes i.e. in the docker build workflow.
Currently WIP checking CI.

2022-09-08 08:38 UTC, luca-della-vedova commented
Nightly fail is due to it trying to build the simulation / demos packages after the rename but the renaming PRs not being merged yet.

If there is any further issue with the nightly builds after the renaming it will be addressed in a future PR.

2022-09-08 09:14 UTC, Yadunund requested changes
Small comments

2022-09-08 09:14 UTC, Yadunund commented on Dockerfile
> +    clang-13 lldb-13 lld-13 \
`Ubuntu 22.04` has `clang-14` so why `13`?

2022-09-08 09:14 UTC, Yadunund commented on README.md
> +**NOTE: RMF does not support building on gcc.**
I wouldn't say this.

```suggestion
**NOTE: We strongly recommend compiling Open-RMF packages with `clang` as compiler and `lld` as linker.**
```

2022-09-08 09:14 UTC, Yadunund commented on README.md
> +CXX=clang++ LDFLAGS='-fuse-ld=lld' colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
We should promote using`colcon mixin`. It's a great tool that users will benefit from.

```suggestion
# Update colcon mixin which is one time step
colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
colcon mixin update default

export CXX=clang++
export CX=clang
colcon build --mixin "release lld"
```

2022-09-08 10:53 UTC, Yadunund approved these changes

2022-09-09 07:34 UTC, orensbruli commented
> her issue with the nightly builds after the renaming it will be addressed in a future P

For reference https://github.com/open-rmf/rmf_demos/pull/155

Is it only needed the sign-off of the last commit to getting it merged?

2022-09-13 03:38 UTC, merged